#' split ownersYYYY and rentersYYYY by city
#' This function creates subsets of renters and owners by city
#' @param arg Defaults to true.
#' @keywords owners, renters, subset
#' @export
#' @examples
#' ownershipByCity()
#' ownershipByCity(TRUE)

ownershipByCity <- function(arg = TRUE) {
  if (arg == TRUE) {

##############  define owners #########################

Ownerjerusalem2004 <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2004    <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2004     <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2004 <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2004    <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Holon")
OwnerLod2004      <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Lod")
OwnerHadera2004   <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2004 <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Ashqelon")
OwnerNettanya2004 <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Nettanya")
OwnerRehovot2004  <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2004    <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2004 <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Raannana")
Ownertlv2004      <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Tel Aviv-Yafo")
Ownerbene2004     <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2004      <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2004    <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2004    <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2004   <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2004    <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2004     <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2004         <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2004     <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2004      <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2004     <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2004      <<- subset(familiesList[[1]], owner=="Yes", codeloc=="Giv'atayim")

Ownerjerusalem2005 <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2005    <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2005     <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2005 <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2005    <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Holon")
OwnerLod2005      <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Lod")
OwnerHadera2005   <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2005 <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Ashqelon")
OwnerNettanya2005 <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Nettanya")
OwnerRehovot2005  <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2005    <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2005 <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Raannana")
Ownertlv2005      <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Tel Aviv-Yafo")
Ownerbene2005     <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2005      <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2005    <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2005    <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2005   <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2005    <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2005     <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2005         <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2005     <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2005      <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2005     <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2005      <<- subset(familiesList[[2]], owner=="Yes", codeloc=="Giv'atayim")


Ownerjerusalem2006 <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2006    <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2006     <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2006 <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2006    <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Holon")
OwnerLod2006      <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Lod")
OwnerHadera2006   <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2006 <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Ashqelon")
OwnerNettanya2006 <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Nettanya")
OwnerRehovot2006  <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2006    <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2006 <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Raannana")
Ownertlv2006      <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Tel Aviv-Yafo")
Ownerbene2006     <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2006      <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2006    <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2006    <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2006   <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2006    <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2006     <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2006         <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2006     <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2006      <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2006     <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2006      <<- subset(familiesList[[3]], owner=="Yes", codeloc=="Giv'atayim")

Ownerjerusalem2007 <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2007    <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2007     <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2007 <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2007    <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Holon")
OwnerLod2007      <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Lod")
OwnerHadera2007   <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2007 <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2007 <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2007  <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2007    <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2007 <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Raannana")
Ownertlv2007      <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2007     <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2007      <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2007    <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2007    <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2007   <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2007    <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2007     <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2007         <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2007     <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2007      <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2007     <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2007      <<- subset(familiesList[[4]], owner=="Yes", codeloc=="Giv'atayim")


Ownerjerusalem2008 <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2008    <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2008     <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2008 <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2008    <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Holon")
OwnerLod2008      <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Lod")
OwnerHadera2008   <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2008 <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2008 <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2008  <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2008    <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2008 <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Raannana")
Ownertlv2008      <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2008     <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2008      <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2008    <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2008    <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2008   <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2008    <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2008     <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2008         <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2008     <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2008      <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2008     <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2008      <<- subset(familiesList[[5]], owner=="Yes", codeloc=="Giv'atayim")

Ownerjerusalem2009 <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2009    <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2009     <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2009 <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2009    <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Holon")
OwnerLod2009      <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Lod")
OwnerHadera2009   <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2009 <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2009 <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2009  <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2009    <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2009 <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Raannana")
Ownertlv2009      <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2009     <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2009      <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2009    <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2009    <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2009   <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2009    <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2009     <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2009         <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2009     <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2009      <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2009     <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2009      <<- subset(familiesList[[6]], owner=="Yes", codeloc=="Giv'atayim")

Ownerjerusalem2010 <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2010    <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2010     <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2010 <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2010    <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Holon")
OwnerLod2010      <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Lod")
OwnerHadera2010   <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2010 <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2010 <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2010  <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2010    <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2010 <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Raannana")
Ownertlv2010      <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2010     <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2010      <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2010    <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2010    <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2010   <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2010    <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2010     <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2010         <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2010     <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2010      <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2010     <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2010      <<- subset(familiesList[[7]], owner=="Yes", codeloc=="Giv'atayim")

Ownerjerusalem2011 <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2011    <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2011     <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2011 <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2011    <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Holon")
OwnerLod2011      <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Lod")
OwnerHadera2011   <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2011 <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2011 <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2011  <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2011    <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2011 <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Raannana")
Ownertlv2011      <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2011     <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2011      <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2011    <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2011    <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2011   <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2011    <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2011     <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2011         <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2011     <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2011      <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2011     <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2011      <<- subset(familiesList[[8]], owner=="Yes", codeloc=="Giv'atayim")


Ownerjerusalem2012 <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2012    <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2012     <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2012 <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2012    <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Holon")
OwnerLod2012      <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Lod")
OwnerHadera2012   <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2012 <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2012 <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2012  <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2012    <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2012 <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Raannana")
Ownertlv2012      <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2012     <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2012      <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2012    <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2012    <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2012   <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2012    <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2012     <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2012         <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2012     <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2012      <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2012     <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2012      <<- subset(familiesList[[9]], owner=="Yes", codeloc=="Giv'atayim")


Ownerjerusalem2013 <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2013    <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2013     <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2013 <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2013    <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Holon")
OwnerLod2013      <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Lod")
OwnerHadera2013   <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2013 <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2013 <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2013  <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2013    <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2013 <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Raannana")
Ownertlv2013      <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2013     <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2013      <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2013    <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2013    <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2013   <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2013    <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2013     <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2013         <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2013     <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2013      <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2013     <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Qiryat Atta")
Ownergivatayim2013      <<- subset(familiesList[[10]], owner=="Yes", codeloc=="Giv'atayim")

Ownerjerusalem2014 <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Jerusalem")
OwnerAshdod2014    <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Ashdod")
OwnerHaifa2014     <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Haifa")
OwnerHerzliyya2014 <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Herzliyya")
OwnerHolon2014    <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Holon")
OwnerLod2014      <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Lod")
OwnerHadera2014   <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Hadera")
OwnerAshqelon2014 <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Ashkelon")
OwnerNettanya2014 <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Netanya")
OwnerRehovot2014  <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Rehovot")
OwnerRamla2014    <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Ramla")
OwnerRaannana2014 <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Raannana")
Ownertlv2014      <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Tel Aviv-Yaffo")
Ownerbene2014     <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Bene Beraq")
Ownerbat2014      <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Bat Yam")
Ownerkefar2014    <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Kefar Sava")
Ownerpetah2014    <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Petah Tiqwa")
Ownerrishon2014   <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Rishon LeZiyon")
Ownerramat2014    <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Ramat Gan")
Ownerbeer2014     <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Beer Sheva")
Ownermodiin2014         <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Modi'in")
Ownerbetshemesh2014     <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Bet Shemesh")
Ownernahariyya2014      <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Nahariyya")
Ownerqiryatatta2014     <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Qiryat Ata")
Ownergivatayim2014      <<- subset(familiesList[[11]], owner=="Yes", codeloc=="Giv'atayim")


##############  define renters  #########################


Renterjerusalem2004 <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2004    <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2004     <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2004 <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2004    <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Holon")
RenterLod2004      <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Lod")
RenterHadera2004   <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2004 <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Ashqelon")
RenterNettanya2004 <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Nettanya")
RenterRehovot2004  <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2004    <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2004 <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Raannana")
Rentertlv2004      <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Tel Aviv-Yafo")
Renterbene2004     <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2004      <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2004    <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2004    <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2004   <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2004    <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2004     <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2004         <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2004     <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2004      <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2004     <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2004      <<- subset(familiesList[[1]], rent == "Yes", codeloc=="Giv'atayim")

Renterjerusalem2005 <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2005    <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2005     <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2005 <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2005    <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Holon")
RenterLod2005      <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Lod")
RenterHadera2005   <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2005 <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Ashqelon")
RenterNettanya2005 <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Nettanya")
RenterRehovot2005  <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2005    <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2005 <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Raannana")
Rentertlv2005      <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Tel Aviv-Yafo")
Renterbene2005     <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2005      <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2005    <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2005    <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2005   <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2005    <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2005     <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2005         <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2005     <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2005      <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2005     <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2005      <<- subset(familiesList[[2]], rent == "Yes", codeloc=="Giv'atayim")


Renterjerusalem2006 <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2006    <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2006     <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2006 <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2006    <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Holon")
RenterLod2006      <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Lod")
RenterHadera2006   <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2006 <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Ashqelon")
RenterNettanya2006 <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Nettanya")
RenterRehovot2006  <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2006    <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2006 <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Raannana")
Rentertlv2006      <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Tel Aviv-Yafo")
Renterbene2006     <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2006      <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2006    <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2006    <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2006   <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2006    <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2006     <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2006         <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2006     <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2006      <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2006     <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2006      <<- subset(familiesList[[3]], rent == "Yes", codeloc=="Giv'atayim")

Renterjerusalem2007 <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2007    <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2007     <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2007 <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2007    <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Holon")
RenterLod2007      <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Lod")
RenterHadera2007   <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2007 <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2007 <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2007  <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2007    <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2007 <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Raannana")
Rentertlv2007      <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2007     <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2007      <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2007    <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2007    <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2007   <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2007    <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2007     <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2007         <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2007     <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2007      <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2007     <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2007      <<- subset(familiesList[[4]], rent == "Yes", codeloc=="Giv'atayim")


Renterjerusalem2008 <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2008    <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2008     <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2008 <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2008    <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Holon")
RenterLod2008      <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Lod")
RenterHadera2008   <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2008 <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2008 <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2008  <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2008    <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2008 <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Raannana")
Rentertlv2008      <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2008     <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2008      <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2008    <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2008    <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2008   <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2008    <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2008     <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2008         <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2008     <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2008      <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2008     <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2008      <<- subset(familiesList[[5]], rent == "Yes", codeloc=="Giv'atayim")

Renterjerusalem2009 <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2009    <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2009     <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2009 <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2009    <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Holon")
RenterLod2009      <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Lod")
RenterHadera2009   <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2009 <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2009 <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2009  <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2009    <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2009 <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Raannana")
Rentertlv2009      <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2009     <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2009      <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2009    <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2009    <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2009   <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2009    <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2009     <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2009         <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2009     <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2009      <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2009     <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2009      <<- subset(familiesList[[6]], rent == "Yes", codeloc=="Giv'atayim")

Renterjerusalem2010 <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2010    <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2010     <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2010 <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2010    <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Holon")
RenterLod2010      <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Lod")
RenterHadera2010   <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2010 <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2010 <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2010  <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2010    <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2010 <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Raannana")
Rentertlv2010      <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2010     <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2010      <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2010    <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2010    <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2010   <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2010    <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2010     <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2010         <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2010     <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2010      <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2010     <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2010      <<- subset(familiesList[[7]], rent == "Yes", codeloc=="Giv'atayim")

Renterjerusalem2011 <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2011    <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2011     <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2011 <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2011    <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Holon")
RenterLod2011      <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Lod")
RenterHadera2011   <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2011 <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2011 <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2011  <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2011    <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2011 <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Raannana")
Rentertlv2011      <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2011     <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2011      <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2011    <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2011    <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2011   <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2011    <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2011     <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2011         <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2011     <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2011      <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2011     <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2011      <<- subset(familiesList[[8]], rent == "Yes", codeloc=="Giv'atayim")


Renterjerusalem2012 <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2012    <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2012     <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2012 <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2012    <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Holon")
RenterLod2012      <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Lod")
RenterHadera2012   <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2012 <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2012 <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2012  <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2012    <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2012 <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Raannana")
Rentertlv2012      <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2012     <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2012      <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2012    <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2012    <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2012   <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2012    <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2012     <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2012         <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2012     <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2012      <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2012     <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2012      <<- subset(familiesList[[9]], rent == "Yes", codeloc=="Giv'atayim")


Renterjerusalem2013 <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2013    <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2013     <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2013 <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2013    <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Holon")
RenterLod2013      <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Lod")
RenterHadera2013   <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2013 <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2013 <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2013  <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2013    <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2013 <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Raannana")
Rentertlv2013      <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2013     <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2013      <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2013    <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2013    <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2013   <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2013    <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2013     <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2013         <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2013     <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2013      <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2013     <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Qiryat Atta")
Rentergivatayim2013      <<- subset(familiesList[[10]], rent == "Yes", codeloc=="Giv'atayim")

Renterjerusalem2014 <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Jerusalem")
RenterAshdod2014    <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Ashdod")
RenterHaifa2014     <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Haifa")
RenterHerzliyya2014 <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Herzliyya")
RenterHolon2014    <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Holon")
RenterLod2014      <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Lod")
RenterHadera2014   <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Hadera")
RenterAshqelon2014 <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Ashkelon")
RenterNettanya2014 <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Netanya")
RenterRehovot2014  <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Rehovot")
RenterRamla2014    <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Ramla")
RenterRaannana2014 <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Raannana")
Rentertlv2014      <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Tel Aviv-Yaffo")
Renterbene2014     <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Bene Beraq")
Renterbat2014      <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Bat Yam")
Renterkefar2014    <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Kefar Sava")
Renterpetah2014    <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Petah Tiqwa")
Renterrishon2014   <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Rishon LeZiyon")
Renterramat2014    <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Ramat Gan")
Renterbeer2014     <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Beer Sheva")
Rentermodiin2014         <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Modi'in")
Renterbetshemesh2014     <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Bet Shemesh")
Renternahariyya2014      <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Nahariyya")
Renterqiryatatta2014     <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Qiryat Ata")
Rentergivatayim2014      <<- subset(familiesList[[11]], rent == "Yes", codeloc=="Giv'atayim")








    } else {
        return("not implemented, error: 990ra9sldoar")
    }
}
