#' subsets the yearly surveys by city of residence
#' @param arg nil
#' @keywords city, subset
#' @export
#' @examples
#' subsetCities()

subsetCities <- function(arg) {

cities <- as.character(levels(renters2004$codeloc))
cityList <<- cities[-1]

jerusalem2004 <<- subset(familiesList[[1]], codeloc=="Jerusalem")
Ashdod2004    <<- subset(familiesList[[1]], codeloc=="Ashdod")
Haifa2004     <<- subset(familiesList[[1]], codeloc=="Haifa")
Herzliyya2004 <<- subset(familiesList[[1]], codeloc=="Herzliyya")
Holon2004    <<- subset(familiesList[[1]], codeloc=="Holon")
Lod2004      <<- subset(familiesList[[1]], codeloc=="Lod")
Hadera2004   <<- subset(familiesList[[1]], codeloc=="Hadera")
Ashqelon2004 <<- subset(familiesList[[1]], codeloc=="Ashqelon")
Nettanya2004 <<- subset(familiesList[[1]], codeloc=="Nettanya")
Rehovot2004  <<- subset(familiesList[[1]], codeloc=="Rehovot")
Ramla2004    <<- subset(familiesList[[1]], codeloc=="Ramla")
Raannana2004 <<- subset(familiesList[[1]], codeloc=="Raannana")
tlv2004      <<- subset(familiesList[[1]], codeloc=="Tel Aviv-Yafo")
bene2004     <<- subset(familiesList[[1]], codeloc=="Bene Beraq")
bat2004      <<- subset(familiesList[[1]], codeloc=="Bat Yam")
kefar2004    <<- subset(familiesList[[1]], codeloc=="Kefar Sava")
petah2004    <<- subset(familiesList[[1]], codeloc=="Petah Tiqwa")
rishon2004   <<- subset(familiesList[[1]], codeloc=="Rishon LeZiyon")
ramat2004    <<- subset(familiesList[[1]], codeloc=="Ramat Gan")
beer2004     <<- subset(familiesList[[1]], codeloc=="Beer Sheva")

jerusalem2005 <<- subset(familiesList[[2]], codeloc=="Jerusalem")
Ashdod2005    <<- subset(familiesList[[2]], codeloc=="Ashdod")
Haifa2005     <<- subset(familiesList[[2]], codeloc=="Haifa")
Herzliyya2005 <<- subset(familiesList[[2]], codeloc=="Herzliyya")
Holon2005    <<- subset(familiesList[[2]], codeloc=="Holon")
Lod2005      <<- subset(familiesList[[2]], codeloc=="Lod")
Hadera2005   <<- subset(familiesList[[2]], codeloc=="Hadera")
Ashqelon2005 <<- subset(familiesList[[2]], codeloc=="Ashqelon")
Nettanya2005 <<- subset(familiesList[[2]], codeloc=="Nettanya")
Rehovot2005  <<- subset(familiesList[[2]], codeloc=="Rehovot")
Ramla2005    <<- subset(familiesList[[2]], codeloc=="Ramla")
Raannana2005 <<- subset(familiesList[[2]], codeloc=="Raannana")
tlv2005      <<- subset(familiesList[[2]], codeloc=="Tel Aviv-Yafo")
bene2005     <<- subset(familiesList[[2]], codeloc=="Bene Beraq")
bat2005      <<- subset(familiesList[[2]], codeloc=="Bat Yam")
kefar2005    <<- subset(familiesList[[2]], codeloc=="Kefar Sava")
petah2005    <<- subset(familiesList[[2]], codeloc=="Petah Tiqwa")
rishon2005   <<- subset(familiesList[[2]], codeloc=="Rishon LeZiyon")
ramat2005    <<- subset(familiesList[[2]], codeloc=="Ramat Gan")
beer2005     <<- subset(familiesList[[2]], codeloc=="Beer Sheva")

jerusalem2006 <<- subset(familiesList[[3]], codeloc=="Jerusalem")
Ashdod2006    <<- subset(familiesList[[3]], codeloc=="Ashdod")
Haifa2006     <<- subset(familiesList[[3]], codeloc=="Haifa")
Herzliyya2006 <<- subset(familiesList[[3]], codeloc=="Herzliyya")
Holon2006    <<- subset(familiesList[[3]], codeloc=="Holon")
Lod2006      <<- subset(familiesList[[3]], codeloc=="Lod")
Hadera2006   <<- subset(familiesList[[3]], codeloc=="Hadera")
Ashqelon2006 <<- subset(familiesList[[3]], codeloc=="Ashqelon")
Nettanya2006 <<- subset(familiesList[[3]], codeloc=="Nettanya")
Rehovot2006  <<- subset(familiesList[[3]], codeloc=="Rehovot")
Ramla2006    <<- subset(familiesList[[3]], codeloc=="Ramla")
Raannana2006 <<- subset(familiesList[[3]], codeloc=="Raannana")
tlv2006      <<- subset(familiesList[[3]], codeloc=="Tel Aviv-Yafo")
bene2006     <<- subset(familiesList[[3]], codeloc=="Bene Beraq")
bat2006      <<- subset(familiesList[[3]], codeloc=="Bat Yam")
kefar2006    <<- subset(familiesList[[3]], codeloc=="Kefar Sava")
petah2006    <<- subset(familiesList[[3]], codeloc=="Petah Tiqwa")
rishon2006   <<- subset(familiesList[[3]], codeloc=="Rishon LeZiyon")
ramat2006    <<- subset(familiesList[[3]], codeloc=="Ramat Gan")
beer2006     <<- subset(familiesList[[3]], codeloc=="Beer Sheva")

jerusalem2007 <<- subset(familiesList[[4]], codeloc=="Jerusalem")
Ashdod2007    <<- subset(familiesList[[4]], codeloc=="Ashdod")
Haifa2007     <<- subset(familiesList[[4]], codeloc=="Haifa")
Herzliyya2007 <<- subset(familiesList[[4]], codeloc=="Herzliyya")
Holon2007    <<- subset(familiesList[[4]], codeloc=="Holon")
Lod2007      <<- subset(familiesList[[4]], codeloc=="Lod")
Hadera2007   <<- subset(familiesList[[4]], codeloc=="Hadera")
Ashqelon2007 <<- subset(familiesList[[4]], codeloc=="Ashqelon")
Nettanya2007 <<- subset(familiesList[[4]], codeloc=="Nettanya")
Rehovot2007  <<- subset(familiesList[[4]], codeloc=="Rehovot")
Ramla2007    <<- subset(familiesList[[4]], codeloc=="Ramla")
Raannana2007 <<- subset(familiesList[[4]], codeloc=="Raannana")
tlv2007      <<- subset(familiesList[[4]], codeloc=="Tel Aviv-Yafo")
bene2007     <<- subset(familiesList[[4]], codeloc=="Bene Beraq")
bat2007      <<- subset(familiesList[[4]], codeloc=="Bat Yam")
kefar2007    <<- subset(familiesList[[4]], codeloc=="Kefar Sava")
petah2007    <<- subset(familiesList[[4]], codeloc=="Petah Tiqwa")
rishon2007   <<- subset(familiesList[[4]], codeloc=="Rishon LeZiyon")
ramat2007    <<- subset(familiesList[[4]], codeloc=="Ramat Gan")
beer2007     <<- subset(familiesList[[4]], codeloc=="Beer Sheva")

jerusalem2008 <<- subset(familiesList[[5]], codeloc=="Jerusalem")
Ashdod2008    <<- subset(familiesList[[5]], codeloc=="Ashdod")
Haifa2008     <<- subset(familiesList[[5]], codeloc=="Haifa")
Herzliyya2008 <<- subset(familiesList[[5]], codeloc=="Herzliyya")
Holon2008    <<- subset(familiesList[[5]], codeloc=="Holon")
Lod2008      <<- subset(familiesList[[5]], codeloc=="Lod")
Hadera2008   <<- subset(familiesList[[5]], codeloc=="Hadera")
Ashqelon2008 <<- subset(familiesList[[5]], codeloc=="Ashqelon")
Nettanya2008 <<- subset(familiesList[[5]], codeloc=="Nettanya")
Rehovot2008  <<- subset(familiesList[[5]], codeloc=="Rehovot")
Ramla2008    <<- subset(familiesList[[5]], codeloc=="Ramla")
Raannana2008 <<- subset(familiesList[[5]], codeloc=="Raannana")
tlv2008      <<- subset(familiesList[[5]], codeloc=="Tel Aviv-Yafo")
bene2008     <<- subset(familiesList[[5]], codeloc=="Bene Beraq")
bat2008      <<- subset(familiesList[[5]], codeloc=="Bat Yam")
kefar2008    <<- subset(familiesList[[5]], codeloc=="Kefar Sava")
petah2008    <<- subset(familiesList[[5]], codeloc=="Petah Tiqwa")
rishon2008   <<- subset(familiesList[[5]], codeloc=="Rishon LeZiyon")
ramat2008    <<- subset(familiesList[[5]], codeloc=="Ramat Gan")
beer2008     <<- subset(familiesList[[5]], codeloc=="Beer Sheva")

jerusalem2009 <<- subset(familiesList[[6]], codeloc=="Jerusalem")
Ashdod2009    <<- subset(familiesList[[6]], codeloc=="Ashdod")
Haifa2009     <<- subset(familiesList[[6]], codeloc=="Haifa")
Herzliyya2009 <<- subset(familiesList[[6]], codeloc=="Herzliyya")
Holon2009    <<- subset(familiesList[[6]], codeloc=="Holon")
Lod2009      <<- subset(familiesList[[6]], codeloc=="Lod")
Hadera2009   <<- subset(familiesList[[6]], codeloc=="Hadera")
Ashqelon2009 <<- subset(familiesList[[6]], codeloc=="Ashqelon")
Nettanya2009 <<- subset(familiesList[[6]], codeloc=="Nettanya")
Rehovot2009  <<- subset(familiesList[[6]], codeloc=="Rehovot")
Ramla2009    <<- subset(familiesList[[6]], codeloc=="Ramla")
Raannana2009 <<- subset(familiesList[[6]], codeloc=="Raannana")
tlv2009      <<- subset(familiesList[[6]], codeloc=="Tel Aviv-Yafo")
bene2009     <<- subset(familiesList[[6]], codeloc=="Bene Beraq")
bat2009      <<- subset(familiesList[[6]], codeloc=="Bat Yam")
kefar2009    <<- subset(familiesList[[6]], codeloc=="Kefar Sava")
petah2009    <<- subset(familiesList[[6]], codeloc=="Petah Tiqwa")
rishon2009   <<- subset(familiesList[[6]], codeloc=="Rishon LeZiyon")
ramat2009    <<- subset(familiesList[[6]], codeloc=="Ramat Gan")
beer2009     <<- subset(familiesList[[6]], codeloc=="Beer Sheva")

jerusalem2010 <<- subset(familiesList[[7]], codeloc=="Jerusalem")
Ashdod2010    <<- subset(familiesList[[7]], codeloc=="Ashdod")
Haifa2010     <<- subset(familiesList[[7]], codeloc=="Haifa")
Herzliyya2010 <<- subset(familiesList[[7]], codeloc=="Herzliyya")
Holon2010    <<- subset(familiesList[[7]], codeloc=="Holon")
Lod2010      <<- subset(familiesList[[7]], codeloc=="Lod")
Hadera2010   <<- subset(familiesList[[7]], codeloc=="Hadera")
Ashqelon2010 <<- subset(familiesList[[7]], codeloc=="Ashqelon")
Nettanya2010 <<- subset(familiesList[[7]], codeloc=="Nettanya")
Rehovot2010  <<- subset(familiesList[[7]], codeloc=="Rehovot")
Ramla2010    <<- subset(familiesList[[7]], codeloc=="Ramla")
Raannana2010 <<- subset(familiesList[[7]], codeloc=="Raannana")
tlv2010      <<- subset(familiesList[[7]], codeloc=="Tel Aviv-Yafo")
bene2010     <<- subset(familiesList[[7]], codeloc=="Bene Beraq")
bat2010      <<- subset(familiesList[[7]], codeloc=="Bat Yam")
kefar2010    <<- subset(familiesList[[7]], codeloc=="Kefar Sava")
petah2010    <<- subset(familiesList[[7]], codeloc=="Petah Tiqwa")
rishon2010   <<- subset(familiesList[[7]], codeloc=="Rishon LeZiyon")
ramat2010    <<- subset(familiesList[[7]], codeloc=="Ramat Gan")
beer2010     <<- subset(familiesList[[7]], codeloc=="Beer Sheva")

jerusalem2011 <<- subset(familiesList[[8]], codeloc=="Jerusalem")
Ashdod2011    <<- subset(familiesList[[8]], codeloc=="Ashdod")
Haifa2011     <<- subset(familiesList[[8]], codeloc=="Haifa")
Herzliyya2011 <<- subset(familiesList[[8]], codeloc=="Herzliyya")
Holon2011    <<- subset(familiesList[[8]], codeloc=="Holon")
Lod2011      <<- subset(familiesList[[8]], codeloc=="Lod")
Hadera2011   <<- subset(familiesList[[8]], codeloc=="Hadera")
Ashqelon2011 <<- subset(familiesList[[8]], codeloc=="Ashqelon")
Nettanya2011 <<- subset(familiesList[[8]], codeloc=="Nettanya")
Rehovot2011  <<- subset(familiesList[[8]], codeloc=="Rehovot")
Ramla2011    <<- subset(familiesList[[8]], codeloc=="Ramla")
Raannana2011 <<- subset(familiesList[[8]], codeloc=="Raannana")
tlv2011      <<- subset(familiesList[[8]], codeloc=="Tel Aviv-Yafo")
bene2011     <<- subset(familiesList[[8]], codeloc=="Bene Beraq")
bat2011      <<- subset(familiesList[[8]], codeloc=="Bat Yam")
kefar2011    <<- subset(familiesList[[8]], codeloc=="Kefar Sava")
petah2011    <<- subset(familiesList[[8]], codeloc=="Petah Tiqwa")
rishon2011   <<- subset(familiesList[[8]], codeloc=="Rishon LeZiyon")
ramat2011    <<- subset(familiesList[[8]], codeloc=="Ramat Gan")
beer2011     <<- subset(familiesList[[8]], codeloc=="Beer Sheva")

jerusalem2012 <<- subset(familiesList[[9]], codeloc=="Jerusalem")
Ashdod2012    <<- subset(familiesList[[9]], codeloc=="Ashdod")
Haifa2012     <<- subset(familiesList[[9]], codeloc=="Haifa")
Herzliyya2012 <<- subset(familiesList[[9]], codeloc=="Herzliyya")
Holon2012    <<- subset(familiesList[[9]], codeloc=="Holon")
Lod2012      <<- subset(familiesList[[9]], codeloc=="Lod")
Hadera2012   <<- subset(familiesList[[9]], codeloc=="Hadera")
Ashqelon2012 <<- subset(familiesList[[9]], codeloc=="Ashqelon")
Nettanya2012 <<- subset(familiesList[[9]], codeloc=="Nettanya")
Rehovot2012  <<- subset(familiesList[[9]], codeloc=="Rehovot")
Ramla2012    <<- subset(familiesList[[9]], codeloc=="Ramla")
Raannana2012 <<- subset(familiesList[[9]], codeloc=="Raannana")
tlv2012      <<- subset(familiesList[[9]], codeloc=="Tel Aviv-Yafo")
bene2012     <<- subset(familiesList[[9]], codeloc=="Bene Beraq")
bat2012      <<- subset(familiesList[[9]], codeloc=="Bat Yam")
kefar2012    <<- subset(familiesList[[9]], codeloc=="Kefar Sava")
petah2012    <<- subset(familiesList[[9]], codeloc=="Petah Tiqwa")
rishon2012   <<- subset(familiesList[[9]], codeloc=="Rishon LeZiyon")
ramat2012    <<- subset(familiesList[[9]], codeloc=="Ramat Gan")
beer2012     <<- subset(familiesList[[9]], codeloc=="Beer Sheva")

jerusalem2013 <<- subset(familiesList[[10]], codeloc=="Jerusalem")
Ashdod2013    <<- subset(familiesList[[10]], codeloc=="Ashdod")
Haifa2013     <<- subset(familiesList[[10]], codeloc=="Haifa")
Herzliyya2013 <<- subset(familiesList[[10]], codeloc=="Herzliyya")
Holon2013    <<- subset(familiesList[[10]], codeloc=="Holon")
Lod2013      <<- subset(familiesList[[10]], codeloc=="Lod")
Hadera2013   <<- subset(familiesList[[10]], codeloc=="Hadera")
Ashqelon2013 <<- subset(familiesList[[10]], codeloc=="Ashqelon")
Nettanya2013 <<- subset(familiesList[[10]], codeloc=="Nettanya")
Rehovot2013  <<- subset(familiesList[[10]], codeloc=="Rehovot")
Ramla2013    <<- subset(familiesList[[10]], codeloc=="Ramla")
Raannana2013 <<- subset(familiesList[[10]], codeloc=="Raannana")
tlv2013      <<- subset(familiesList[[10]], codeloc=="Tel Aviv-Yafo")
bene2013     <<- subset(familiesList[[10]], codeloc=="Bene Beraq")
bat2013      <<- subset(familiesList[[10]], codeloc=="Bat Yam")
kefar2013    <<- subset(familiesList[[10]], codeloc=="Kefar Sava")
petah2013    <<- subset(familiesList[[10]], codeloc=="Petah Tiqwa")
rishon2013   <<- subset(familiesList[[10]], codeloc=="Rishon LeZiyon")
ramat2013    <<- subset(familiesList[[10]], codeloc=="Ramat Gan")
beer2013     <<- subset(familiesList[[10]], codeloc=="Beer Sheva")

jerusalem2014 <<- subset(familiesList[[11]], codeloc=="Jerusalem")
Ashdod2014    <<- subset(familiesList[[11]], codeloc=="Ashdod")
Haifa2014     <<- subset(familiesList[[11]], codeloc=="Haifa")
Herzliyya2014 <<- subset(familiesList[[11]], codeloc=="Herzliyya")
Holon2014    <<- subset(familiesList[[11]], codeloc=="Holon")
Lod2014      <<- subset(familiesList[[11]], codeloc=="Lod")
Hadera2014   <<- subset(familiesList[[11]], codeloc=="Hadera")
Ashqelon2014 <<- subset(familiesList[[11]], codeloc=="Ashqelon")
Nettanya2014 <<- subset(familiesList[[11]], codeloc=="Nettanya")
Rehovot2014  <<- subset(familiesList[[11]], codeloc=="Rehovot")
Ramla2014    <<- subset(familiesList[[11]], codeloc=="Ramla")
Raannana2014 <<- subset(familiesList[[11]], codeloc=="Raannana")
tlv2014      <<- subset(familiesList[[11]], codeloc=="Tel Aviv-Yafo")
bene2014     <<- subset(familiesList[[11]], codeloc=="Bene Beraq")
bat2014      <<- subset(familiesList[[11]], codeloc=="Bat Yam")
kefar2014    <<- subset(familiesList[[11]], codeloc=="Kefar Sava")
petah2014    <<- subset(familiesList[[11]], codeloc=="Petah Tiqwa")
rishon2014   <<- subset(familiesList[[11]], codeloc=="Rishon LeZiyon")
ramat2014    <<- subset(familiesList[[11]], codeloc=="Ramat Gan")
beer2014     <<- subset(familiesList[[11]], codeloc=="Beer Sheva")
}
